name: flutter_rpg
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_core: ^2.18.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  provider: ^6.1.5
  cloud_firestore: ^4.17.5

flutter:  
  uses-material-design: true
  assets:
    - assets/images/Vocations/marauder.jpg
    - assets/images/Vocations/prisoner.jpg
    - assets/images/Vocations/spectator.jpg
    - assets/images/Vocations/lawyer.jpg
    - assets/images/Skills/BrainWash.jpg
    - assets/images/Skills/distortion.jpg
    - assets/images/Skills/observe.jpg
    - assets/images/Skills/quick_attack.jpg
    - assets/images/Skills/zombie_transformation.jpg
    - assets/images/Skills/AcendedTheft.jpg
    - assets/images/Skills/followers.jpg
    - assets/images/Skills/DragonMight.jpg